### ISSUE TITLE
support INSERT DATA operation

### ISSUE THREAD

**Issue by davasqueza** [rdf-ext/rdf-sparql-builder#19]
Currently [rdf-sparql-builder](https://github.com/rdf-ext/rdf-sparql-builder) supports [DELETE](https://github.com/rdf-ext/rdf-sparql-builder/blob/master/lib/Delete.js) operation, would be really useful to support also [INSERT DATA](https://www.w3.org/TR/sparql11-update/#insertData).

I'm open to create a PR for this :)

**Comment by bergos** [comment]
Sure, a PR is very welcome!

**Comment by davasqueza** [comment]
Done! My PR is ready #20, please take a look and let me know if I should change anything.
